name: flutternav
description: A Flutter package to simplify the use of the navigation and routing system that works consistently across all platforms.
version: 0.2.1
homepage: https://github.com/Bewond/flutternav
repository: https://github.com/Bewond/flutternav

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #
  pedantic: ^1.11.0
  vrouter: ^1.1.0+15

dev_dependencies:
  flutter_test:
    sdk: flutter
